default_settings:
  subbly.shop_name:
    type: string
    value: My first Subbly Shop

  subbly.contact_email:
    type: string
    value: contact@subbly.fr

  subbly.shop_currency:
    type: string
    value: EUR

  subbly.backend_language:
    type: string
    value: fr

  subbly.shop_status:
    type: string
    value: offline

  subbly.payment.stripe.active:
    type: string
    value: 0

  subbly.payment.stripe.key:
    type: string
    value: null

  subbly.payment.paypal_express.active:
    type: string
    value: 0

  subbly.payment.paypal_express.username:
    type: string
    value: null

  subbly.payment.paypal_express.password:
    type: string
    value: null

  subbly.payment.paypal_express.signature:
    type: string
    value: null

  subbly.payment.paypal_express.testmode:
    type: boolean
    value: 0